# Choose an existing folder where all downloaded and created datasets will be saved
data_root = "~/datasets/"  # example path
# path to /vol/repl261-vol4/naoth/logs on the instituts gruenau servers
# if your not running the scripts on those servers mount the path /vol/repl261-vol4/naoth/logs locally
# for example with sshfs and use the local path as value
logs_root = "/mnt/logs"  # example path
dataset_root = "/mnt/datasets"  # example path
models_root = "/mnt/models"  # example path

# cvat credentials
cvat_user = ""
cvat_pass = ""