[yolov4_tiny]
# general
TRAIN_YOLO_TINY = true
YOLO_ANCHOR_PER_SCALE = 3
YOLO_MAX_BBOX_PER_SCALE = 100

# values for train dataset generation
TRAIN_CLASSES = "../data/finished/44/obj.names"
TRAIN_ANNOT_PATH = "../data/finished/44/train.txt"

TRAIN_INPUT_SIZE = 416
TRAIN_BATCH_SIZE = 4
TRAIN_DATA_AUG = false

# values for test dataset generation
TEST_ANNOT_PATH = "../data/finished/44/train.txt"
TEST_INPUT_SIZE = 416
TEST_BATCH_SIZE = 4
TEST_DATA_AUG = false

[yolov4]
TRAIN_CLASSES = "../data/finished/44/obj.names"
TRAIN_ANNOT_PATH = "../data/finished/44/train.txt"
TEST_ANNOT_PATH = "../data/finished/44/train.txt"
