# Classification stuff
[classification_1]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification_16x16.pkl"
batch_size = 64
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

# Classification stuff
[classification_1_no_mean]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification_16x16.pkl"
batch_size = 64
epochs = 30
mean_subtraction = false
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_2]
model_name = "naoth_classification2"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification.pkl"
batch_size = 64
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_2_no_mean]
model_name = "naoth_classification2"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification.pkl"
batch_size = 64
epochs = 30
mean_subtraction = false
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_tk_natural]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_natural_classification.pkl"
batch_size = 64
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_tk_synthetic]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_synthetic_classification.pkl"
batch_size = 64
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_tk_combined]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_combined_classification.pkl"
batch_size = 16
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_tk_combined-balanced]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_combined_balanced_classification.pkl"
batch_size = 16
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "/home/stella/Documents/datasets/data_balldetection/naoth"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_rc19_16_bw]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "rc19_classification_16_bw.pkl"
batch_size = 16
epochs = 30
mean_subtraction = true
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "/home/stella/Documents/datasets/data_balldetection/naoth"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false