# Classification stuff
[classification_1]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification_16x16.pkl"
batch_size = 16
epochs = 30
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false


[classification_2]
model_name = "naoth_classification2"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "bhuman_classification.pkl"
batch_size = 16
epochs = 30
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_3]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_synthetic_classification.pkl"
batch_size = 16
epochs = 30
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_4]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_natural_classification.pkl"
batch_size = 16
epochs = 30
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false

[classification_5]
model_name = "naoth_classification1"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_combined_classification.pkl"
batch_size = 16
epochs = 30
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

data_root_path = "../data_balldetection"
output_path = "models"

##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false