name: test-detectron2
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pywin32
  - cudatoolkit=11.2
  - pytorch==1.10.0
  - torchvision
  - git
  - pip
  - pip:
    - git+https://github.com/facebookresearch/detectron2.git